"""
Create or update a dashboard account
====================================

Hashes the password with PBKDF2-SHA256 and writes the account to
``.streamlit/secrets.toml`` (which is ignored by git, so passwords never
end up in the repository).

Usage
-----
    python scripts/create_user.py admin
    python scripts/create_user.py officer1 --name "Traffic Officer"
    python scripts/create_user.py officer1 --delete
"""

from __future__ import annotations

import argparse
import getpass
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "app"))

from auth import hash_password  # noqa: E402

SECRETS = ROOT / ".streamlit" / "secrets.toml"


def read_accounts() -> dict[str, dict[str, str]]:
    """Parse the [auth.users.*] tables written by this script."""
    accounts, current = {}, None
    if not SECRETS.exists():
        return accounts
    for line in SECRETS.read_text(encoding="utf-8").splitlines():
        header = re.match(r"\[auth\.users\.([a-z0-9_.-]+)\]", line.strip())
        if header:
            current = header.group(1)
            accounts[current] = {}
            continue
        field = re.match(r'(\w+)\s*=\s*"(.*)"', line.strip())
        if current and field:
            accounts[current][field.group(1)] = field.group(2)
    return accounts


def write_accounts(accounts: dict[str, dict[str, str]]) -> None:
    SECRETS.parent.mkdir(exist_ok=True)
    lines = ["# Dashboard accounts - generated by scripts/create_user.py. Do not commit.", ""]
    for username, fields in sorted(accounts.items()):
        lines.append(f"[auth.users.{username}]")
        for key, value in fields.items():
            lines.append(f'{key} = "{value}"')
        lines.append("")
    SECRETS.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("username")
    parser.add_argument("--name", help="Display name shown in the dashboard")
    parser.add_argument("--delete", action="store_true", help="Remove the account")
    args = parser.parse_args()

    username = args.username.strip().lower()
    if not re.fullmatch(r"[a-z0-9_.-]{3,32}", username):
        sys.exit("Usernames must be 3-32 characters: lowercase letters, digits, dot, dash or underscore.")

    accounts = read_accounts()
    if args.delete:
        if accounts.pop(username, None) is None:
            sys.exit(f"No account named {username}.")
        write_accounts(accounts)
        print(f"Deleted {username}.")
        return

    password = getpass.getpass("Password (min. 8 characters): ")
    if len(password) < 8:
        sys.exit("Password is too short.")
    if getpass.getpass("Repeat password: ") != password:
        sys.exit("Passwords do not match.")

    name = args.name or accounts.get(username, {}).get("name") or username.title()
    accounts[username] = {"name": name, "password": hash_password(password)}
    write_accounts(accounts)
    print(f"Saved {username} to {SECRETS.relative_to(ROOT)}. Restart the dashboard to apply.")


if __name__ == "__main__":
    main()
